Assignment 3 ProductUnitWebApi/WebApplication2/WebApplication2/Controllers/ProductMVCController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Net.Http;
using WebApplication2.Models;
using System.Web.Mvc;

namespace WebApplication2.Controllers
{
    public class ProductMVCController : Controller
    {
        // GET: ProductMVC
        HttpClient client = new HttpClient();
        public ActionResult Index()
        {
            List<ProductTB> prod_list = new List<ProductTB>();
            client.BaseAddress = new Uri("https://localhost:44350/api/ProductApi");
            var response = client.GetAsync("ProductApi");
            response.Wait();

            var test = response.Result;
            if (test.IsSuccessStatusCode)
            {
                var display = test.Content.ReadAsAsync<List<ProductTB>>();
                display.Wait();
                prod_list = display.Result;
            }
            return View(prod_list);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(ProductTB prod)
        {
            client.BaseAddress = new Uri("https://localhost:44350/Api/ProductApi");
            var response = client.PostAsJsonAsync<ProductTB>("ProductApi", prod);
            response.Wait();

            var test = response.Result;
            if (test.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return View("Create");
        }

        public ActionResult Add(ProductTB s)
        {
            ProductDetails1Entities db = new ProductDetails1Entities();
            db.ProductTBs.Add(s);
            db.SaveChanges();
            db.Dispose();
            return Redirect("Index");
        }

        public ActionResult Details(int id)
        {
            ProductTB p = null;
            client.BaseAddress = new Uri("https://localhost:44350/Api/ProductApi");
            var response = client.GetAsync("ProductApi?id=" + id.ToString());
            response.Wait();

            var test = response.Result;
            if (test.IsSuccessStatusCode)
            {
                var display = test.Content.ReadAsAsync<ProductTB>();
                display.Wait();
                p = display.Result;
            }
            return View(p);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            ProductTB p = null;
            client.BaseAddress = new Uri("https://localhost:44350/Api/ProductApi");
            var response = client.GetAsync("ProductApi?id=" + id.ToString());
            response.Wait();

            var test = response.Result;
            if (test.IsSuccessStatusCode)
            {
                var display = test.Content.ReadAsAsync<ProductTB>();
                display.Wait();
                p = display.Result;
            }
            return View(p);
        }
        [HttpPost]
        public ActionResult Edit(ProductTB p)
        {
            client.BaseAddress = new Uri("https://localhost:44350/Api/ProductApi");
            var response = client.PutAsJsonAsync<ProductTB>("Product", p);
            response.Wait();
            var test = response.Result;
            if (test.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return View("Edit");
        }

        public ActionResult Save(ProductTB s)
        {
            ProductDetails1Entities db = new ProductDetails1Entities();
            ProductTB p = db.ProductTBs.Where(x => x.Product_ID == s.Product_ID).FirstOrDefault();
            p.Product_Name = s.Product_Name;
            p.Price = s.Price;
            p.Category_Id = s.Category_Id;
            p.Unit_Id = s.Unit_Id;
            db.SaveChanges();
            db.Dispose();
            return Redirect("Index");
        }

        public ActionResult Delete(int id)
        {
            ProductTB p = null;
            client.BaseAddress = new Uri("https://localhost:44350/Api/ProductApi");
            var response = client.GetAsync("ProductApi?id=" + id.ToString());
            response.Wait();

            var test = response.Result;
            if (test.IsSuccessStatusCode)
            {
                var display = test.Content.ReadAsAsync<ProductTB>();
                display.Wait();
                p = display.Result;
            }
            return View(p);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            client.BaseAddress = new Uri("https://localhost:44350/Api/ProductApi");
            var response = client.DeleteAsync("ProductApi/" + id.ToString());
            response.Wait();
            var test = response.Result;
            if (test.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return View("Delete");

        }
    }
}

Assignment 3 ProductUnitWebApi/WebApplication2/WebApplication2/Views/ProductMVC/Create.cshtml
@model WebApplication2.Models.ProductTB

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Add", "ProductMVC", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Product_ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Product_ID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Product_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Product_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Product_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Product_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Category_Id, "Category_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @{
                    WebApplication2.Models.ProductDetails1Entities db = new WebApplication2.Models.ProductDetails1Entities();
                    List<WebApplication2.Models.CategoryTB> ListCategory = db.CategoryTBs.ToList();
                    <select name="Category_Td" class="form-control">
                        @{
                            <option value="" disabled hidden selected>Select Category</option>
                            foreach (WebApplication2.Models.CategoryTB s in ListCategory)
                            {
                                <option value="@s.Category_ID">@s.Category_Name</option>
                            }
                        }
                    </select>
                }
                @Html.ValidationMessageFor(model => model.Category_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Unit_Id, "Unit_ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @{
                    WebApplication2.Models.ProductDetails1Entities bd = new WebApplication2.Models.ProductDetails1Entities();
                    List<WebApplication2.Models.UnitTB> ListUnit = bd.UnitTBs.ToList();
                    <select name="Unit_ID" class="form-control">
                        @{
                            <option value="" disabled hidden selected>Select Unit </option>
                            foreach (WebApplication2.Models.UnitTB s in ListUnit)
                            {
                                <option value="@s.Unit_ID">@s.Unit_Name</option>
                            }
                        }
                    </select>
                }
                @Html.ValidationMessageFor(model => model.Unit_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Assignment 3 ProductUnitWebApi/WebApplication2/WebApplication2/Views/ProductMVC/Delete.cshtml
@model WebApplication2.Models.ProductTB

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Product_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CategoryTB.Category_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategoryTB.Category_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UnitTB.Unit_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UnitTB.Unit_Name)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Assignment 3 ProductUnitWebApi/WebApplication2/WebApplication2/Views/ProductMVC/Details.cshtml
@model WebApplication2.Models.ProductTB

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Product_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CategoryTB.Category_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategoryTB.Category_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UnitTB.Unit_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UnitTB.Unit_Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Product_ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Assignment 3 ProductUnitWebApi/WebApplication2/WebApplication2/Views/ProductMVC/Edit.cshtml
@model WebApplication2.Models.ProductTB

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Save", "ProductMVC", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Product_ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Product_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Product_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Product_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Category_Id, "Category_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @{
                    WebApplication2.Models.ProductDetails1Entities db = new WebApplication2.Models.ProductDetails1Entities();
                    List<WebApplication2.Models.CategoryTB> ListCategory = db.CategoryTBs.ToList();
                    <select name="Category_Id" class="form-control">
                        @{
                            <option value="" disabled hidden selected>Select Category</option>
                            foreach (WebApplication2.Models.CategoryTB s in ListCategory)
                            {
                                <option value="@s.Category_ID">@s.Category_Name</option>
                            }
                        }
                    </select>
                }
                @Html.ValidationMessageFor(model => model.Category_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Unit_Id, "Unit_ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @{
                    WebApplication2.Models.ProductDetails1Entities bd = new WebApplication2.Models.ProductDetails1Entities();
                    List<WebApplication2.Models.UnitTB> ListUnit = bd.UnitTBs.ToList();
                    <select name="Unit_ID" class="form-control">
                        @{
                            <option name="" disabled hidden selected>Select Unit </option>
                            foreach (WebApplication2.Models.UnitTB s in ListUnit)
                            {
                                <option value="@s.Unit_ID">@s.Unit_Name</option>
                            }
                        }
                    </select>
                }
                @Html.ValidationMessageFor(model => model.Unit_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Assignment 3 ProductUnitWebApi/WebApplication2/WebApplication2/Views/ProductMVC/Index.cshtml
@model IEnumerable<WebApplication2.Models.ProductTB>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Product_ID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Product_Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            Category ID
        </th>
        <th>
            Unit Id
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Product_ID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Product_Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category_Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Unit_Id)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Product_ID }) |
                @Html.ActionLink("Details", "Details", new { id = item.Product_ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Product_ID })
            </td>
        </tr>
    }

</table>