Assignment 4 BlackJack Game/BlackJackAssignmentMVC/BlackJackAssignmentMVC/Controllers/GamePlayController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BlackJackAssignmentMVC.Models;

namespace BlackJackAssignmentMVC.Controllers
{
    public class GamePlayController : Controller
    {
        BlackJackDatabaseEntities bjde = new BlackJackDatabaseEntities();
        
        // GET: GamePlay
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GameStart()
        {
            CardsDealt cd = new CardsDealt();
            TempData["PlayerCard1"] = cd.PlayerFirstCard();
            TempData["PlayerCard2"] = cd.PlayerSecondCard();
            TempData["DealerCard"] = cd.DealerCards();
            return View();
        }

        public ActionResult Hit()
        {
            HitFunction hf = new HitFunction();
            if (GameScore.PlayerHitCount < 1)
            {
                TempData["PlayerHitCard1"] = hf.PlayerHit();
                GameScore.PlayerHitCount = GameScore.PlayerHitCount + 1;
            }

            else if (GameScore.PlayerHitCount < 2)
            {
                TempData["PlayerHitCard2"] = hf.PlayerHit();
                GameScore.PlayerHitCount = GameScore.PlayerHitCount + 1;
            }

            else if (GameScore.PlayerHitCount < 3)
            {
                TempData["PlayerHitCard3"] = hf.PlayerHit();
            }
            return View("GameStart");
        }

        public ActionResult Stand()
        {
            MainFunctionFOrWinOrLoose mfwl = new MainFunctionFOrWinOrLoose();
            HitFunction hf = new HitFunction();
            while (GameScore.Dealerscore <= 17)
            {
                if (GameScore.DealerHitCount < 1)
                {
                    TempData["DealerHitCard1"] = hf.DealerHit();
                    GameScore.DealerHitCount = GameScore.DealerHitCount + 1;
                }

                else if (GameScore.DealerHitCount < 2)
                {
                    TempData["DealerHitCard2"] = hf.DealerHit();
                    GameScore.DealerHitCount = GameScore.DealerHitCount + 1;
                }
                else if (GameScore.DealerHitCount < 3)
                {
                    TempData["DealerHitCard3"] = hf.DealerHit();
                    GameScore.DealerHitCount = GameScore.DealerHitCount + 1;
                }
                else if (GameScore.DealerHitCount < 4)
                {
                    TempData["DealerHitCard4"] = hf.DealerHit();
                }
            }
            if (GameScore.Dealerscore >= 17 || GameScore.Playerscore >= 21)
            {
                ViewData["GameStatus"] = mfwl.CheckGameStatus();
            }
            return View("GameStart");
        }

        public ActionResult PlayAgain()
        {
            RestartGame rg = new RestartGame();
            rg.Restart();
            TempData.Remove("PlayerhitCard1");
            TempData.Remove("PlayerhitCard2");
            TempData.Remove("PlayerhitCard3");
            TempData.Remove("DealerhitCard1");
            TempData.Remove("DealerhitCard2");
            TempData.Remove("DealerhitCard3");
            TempData.Remove("DealerhitCard4");
            return RedirectToAction("GameStart");
        }

        public ActionResult SessionReport()
        {
            List<SessionTable> session = bjde.SessionTables.ToList();
            return View(session);
        }

        public ActionResult GameSave()
        {
            MainFunctionFOrWinOrLoose mfwl = new MainFunctionFOrWinOrLoose();
            SessionTable ss = new SessionTable();
            ss.PlayerScore = GameScore.Playerscore;
            ss.DealerScore = GameScore.Dealerscore;
            ss.GameResult = mfwl.CheckGameStatus();
            bjde.SessionTables.Add(ss);
            bjde.SaveChanges();
            return View("GameStart");
        }
    }
}

Assignment 4 BlackJack Game/BlackJackAssignmentMVC/BlackJackAssignmentMVC/Views/GamePlay/GameStart.cshtml
@model BlackJackAssignmentMVC.Models.CardsDealt

@{
    ViewBag.Title = "GameStart";
}
<center>
    <h1><b><u>BlackJack Game</u></b></h1>
    <br /><br />
</center>
<button type="button" style="font-size:larger; margin-right:60px" value="Hit" class="body-content" onclick="location.href ='@Url.Action("Hit", "GamePlay")'"><b>Hit</b></button>
<button type="button" style="font-size:larger; margin-left:60px" value="Stand" onclick="location.href ='@Url.Action("Stand", "GamePlay")'"><b>Stand</b></button>

<br />
<br />

<table border="4">
    <style>
        th, td {
            padding: 15px;
            text-align: center;
            border-bottom: 1px solid;
        }

        th {
            font-size: larger;
            color: black;
        }
    </style>
    <tr>
        <th><b>PlayerCards</b></th>
        <th><b>DealerCards</b></th>
    </tr>
    <tr>
        <td>
            @{
                <b>@TempData.Peek("PlayerCard1")</b>
                TempData.Keep("PlayerCard1");
            }
        </td>
        <td>
            @{
                <b>@TempData.Peek("DealerCard")</b>
                TempData.Keep("DealerCard");
            }
        </td>
    </tr>
    <tr>
        <td>
            @{
                <b>@TempData.Peek("PlayerCard2")</b>
                TempData.Keep("PlayerCard2");
            }
        </td>
        <td>
            @{
                <b>@TempData.Peek("DealerhitCard1")</b>
                TempData.Keep("DealerhitCard1");
            }
        </td>
    </tr>
    <tr>
        <td>
            @{
                <b>@TempData.Peek("PlayerHitCard1")</b>
                TempData.Keep("PlayerHitCard1");
            }
        </td>
        <td>
            @{
                <b>@TempData.Peek("DealerhitCard2")</b>
                TempData.Keep("DealerhitCard2");
            }
        </td>
    </tr>
    <tr>
        <td>
            @{
                <b>@TempData.Peek("PlayerHitCard2")</b>
                TempData.Keep("PlayerHitCard2");
            }
        </td>
        <td>
            @{
                <b>@TempData.Peek("DealerHitCard3")</b>
                TempData.Keep("DealerHitCard3");
            }
        </td>
    </tr>
    <tr>
        <td>
            @{
                <b>@TempData.Peek("PlayerHitCard3")</b>
                TempData.Keep("PlayerHitCard3");
            }
        </td>
        <td>
            @{
                <b>@TempData.Peek("DealerHitCard4")</b>
                TempData.Keep("DealerHitCard4");
            }
        </td>
    </tr>
</table>

<br />
<h3>
    <label for="PlayerScore">Player Score:@BlackJackAssignmentMVC.Models.GameScore.Playerscore</label>
    <br />
    <label for="DealerScore">Dealer Score:@BlackJackAssignmentMVC.Models.GameScore.Dealerscore</label>
    <br />
    <label for="Game Status">Game Status:@ViewData["GameStatus"]</label>
</h3>
<br />
<button type="button" style="font-size:larger;" value="Report" onclick="location.href ='@Url.Action("SessionReport","GamePlay")'"><b>View Session Report</b></button>
<button type="button" style="font-size: larger; margin-left:20px" value="Restart" onclick="location.href ='@Url.Action("PlayAgain","GamePlay")'"><b>Play Again</b></button>
<button type="button" style="font-size: larger; margin-left:20px" value="save" onclick="location.href ='@Url.Action("GameSave","GamePlay")'"><b>Save</b></button>

Assignment 4 BlackJack Game/BlackJackAssignmentMVC/BlackJackAssignmentMVC/Views/GamePlay/SessionReport.cshtml
@model IEnumerable<BlackJackAssignmentMVC.Models.SessionTable>

@{
    ViewBag.Title = "SessionReport";
}
@*
<h2>SessionReport</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>*@

<center>
<h1><b> Session Report </b></h1>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Session_No)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PlayerScore)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DealerScore)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.GameResult)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Session_No)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.PlayerScore)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.DealerScore)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.GameResult)
    </td>
    @*<td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Session_No }) |
            @Html.ActionLink("Details", "Details", new { id=item.Session_No }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Session_No })
        </td>*@
</tr>
}

</table>
    </center>